=== tarun-ks/HHSA_2.0/Legacy code/HHSPortal/r2_src/com/nyc/hhs/config/business-rule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://localhost:7001/R2/portal/hhsweb.portal/business-rule"
	elementFormDefault="qualified">

	<xs:element name="rules">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded" minOccurs="0">
				<xs:element type="ruleType" name="rule" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="unique-id">
			<xs:selector xpath="rule" />
			<xs:field xpath="@id" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="ruleType" mixed="true">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element type="expressionType" name="expression" />
		</xs:sequence>
		<xs:attribute name="id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[a-zA-Z0-9]+" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="expressionType" mixed="true">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element type="expressionType" name="expression" />
		</xs:sequence>
		<xs:attribute name="method" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="equals" />
					<xs:enumeration value="notEquals" />
					<xs:enumeration value="greaterThan" />
					<xs:enumeration value="notGreaterThan" />
					<xs:enumeration value="greaterThanEquals" />
					<xs:enumeration value="lessThan" />
					<xs:enumeration value="notLessThan" />
					<xs:enumeration value="lessThanEquals" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="channel_variable" type="xs:string" use="optional" />
		<xs:attribute name="channel_variable2" type="xs:string"	use="optional" />
		<xs:attribute type="xs:string" name="value" use="optional" />
		<xs:attribute name="type" use="optional" default="String">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="String" />
					<xs:enumeration value="Integer" />
					<xs:enumeration value="Float" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="operator" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="and" />
					<xs:enumeration value="or" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

</xs:schema>

=== tarun-ks/HHSA_2.0/Legacy code/HHSPortal/r2_src/com/nyc/hhs/config/business-rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<rules
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="business-rule.xsd">
	<rule id="DisableProposalDetails">
		<expression operator="or">
			<expression channel_variable="procurementStatus" method="equals" type="Integer" value="7" />
			<expression operator="and">
				<expression channel_variable="proposalStatus" method="notEquals" type="Integer" value="17" />
				<expression channel_variable="proposalStatus" method="notEquals" type="Integer" value="19" />
			</expression>
		</expression>
	</rule>
	<rule id="showProposalCommentLinkPropDetalis">
		<expression operator="and">
			<expression channel_variable="commentSize" method="greaterThan" type="Integer" value="0" />
			<expression channel_variable="proposalStatus" method="notEquals" type="Integer" value="17" />
			<expression channel_variable="proposalStatus" method="notEquals" type="Integer" value="18" />
		</expression>
	</rule>
	<rule id="DisableGenerateListButton">
		<expression operator="and">
			<expression channel_variable="status" method="notEquals" type="Integer" value="4" />
			<expression channel_variable="status" method="notEquals" type="Integer" value="5" />
			<expression channel_variable="status" method="notEquals" type="Integer" value="6" />
			<expression channel_variable="status" method="notEquals" type="Integer" value="7" />
			<expression channel_variable="status" method="notEquals" type="Integer" value="8" />
		</expression>
	</rule>
	<rule id="DisableSelectionBoxDropDown">
		<expression operator="or">
			<expression channel_variable="status" method="equals" type="Integer" value="1" />
			<expression channel_variable="status" method="equals" type="Integer" value="2" />
		</expression>
	</rule>
	<rule id="testRule1">
		<expression operator="or">
			<expression channel_variable="testChVarString" method="equals" type="String" value="helloTest" />
		</expression>
	</rule>
	<rule id="testRule2">
		<expression channel_variable="testChVar" method="equals"
			type="String" value="helloTest" />
	</rule>
	<rule id="testRule3">
		<expression operator="or">
			<expression channel_variable="testChVarInteger" method="equals"
				type="Integer" value="10" />
			<expression channel_variable="testChVarFloat" method="equals"
				type="Float" value="11.5" />
			<expression channel_variable="testChVarInteger" method="greaterThanEquals"
				type="Integer" value="10" />
			<expression channel_variable="testChVarString"
				channel_variable2="testChVarString2" method="equals" type="String" />

			<expression operator="and">
				<expression channel_variable="testChVarInteger"
					channel_variable2="testChVarInteger2" method="greaterThanEquals"
					type="Integer" />
				<expression channel_variable="testChVarInteger"
					channel_variable2="testChVarInteger3" method="lessThanEquals" type="Integer" />
				<expression channel_variable="testChVarInteger"
					channel_variable2="testChVarInteger4" method="lessThan" type="Integer" />
				<expression channel_variable="testChVarInteger"
					channel_variable2="testChVarInteger5" method="notGreaterThan" type="Integer" />
			</expression>

			<expression operator="and">
				<expression channel_variable="testChVarFloat"
					channel_variable2="testChVarFloat2" method="greaterThanEquals"
					type="Float" />
				<expression channel_variable="testChVarFloat"
					channel_variable2="testChVarFloat3" method="lessThanEquals" type="Float" />
				<expression channel_variable="testChVarFloat"
					channel_variable2="testChVarFloat4" method="lessThan" type="Float" />
				<expression channel_variable="testChVarFloat"
					channel_variable2="testChVarFloat5" method="greaterThan" type="Float" />
				<expression channel_variable="testChVarFloat"
					channel_variable2="testChVarFloat6" method="notLessThan" type="Float" />
				<expression channel_variable="testChVarFloat"
					channel_variable2="testChVarFloat7" method="notGreaterThan" type="Float" />
			</expression>


			<expression operator="and">
				<expression channel_variable="testChVarInteger"
					channel_variable2="testChVarInteger2" method="greaterThanEquals"
					type="Integer" />
				<expression channel_variable="testChVarInteger"
					channel_variable2="testChVarInteger2" method="lessThanEquals" type="Integer" />
				<expression channel_variable="testChVarFloat"
					channel_variable2="testChVarFloat2" method="lessThan" type="Float" />
				<expression channel_variable="testChVarInteger"
					channel_variable2="testChVarInteger2" method="notGreaterThan" type="Integer" />
			</expression>
		</expression>
	</rule>
	<rule id="testRule3a">
		<expression operator="and">
			<expression channel_variable="testChVarInteger" method="equals"
				type="Integer" value="10" />
			<expression channel_variable="testChVarInteger"
				channel_variable2="testChVarInteger2" method="notEquals" type="Integer" />
		</expression>
	</rule>
	
	<rule id="testRule4StringEqualsHandler1">
		<expression channel_variable="testChVar" method="equals" type="String" value="helloTest" />
	</rule>
	
	<rule id="testRule4StringEqualsHandler2">
		<expression channel_variable="testChVar" channel_variable2="testChVar2" method="equals" type="String"/>
	</rule>	
	
	<rule id="testRule4StringNotEqualsHandler1">
		<expression channel_variable="testChVar" method="notEquals" type="String" value="helloTest" />
	</rule>
	
	<!-- Contract Budget List starts -->
	<rule id="contractList1">
		<expression method="equals" channel_variable="status"
			value="Registered" type="String" />
	</rule>
	<rule id="contractList2">
		<expression method="equals" channel_variable="status"
			value="Pending Registration" type="String" />
			<!--  begin R6.3 QC5690  new contract code Pending Notification 
		<expression operator="or">
			<expression method="equals" channel_variable="status"
				value="Pending Registration" type="String" />
			<expression method="equals" channel_variable="status"
				value="Pending Notification" type="String" />
		</expression>	
		-->
	 <!--  end R6.3 QC5690  new contract code Pending Notification	-->
	</rule>
	<rule id="contractList3">
		<expression method="equals" channel_variable="status"
			value="Suspended" type="String" />
	</rule>
	<rule id="contractList4">
		<expression operator="or">
			<expression method="equals" channel_variable="status"
				value="Cancelled" type="String" />
			<expression method="equals" channel_variable="status"
				value="Closed" type="String" />
		</expression>
	</rule>
	<rule id="contractList5">
		<expression operator="or">
			<expression method="equals" channel_variable="status"
				value="Pending Configuration" type="String" />
			<expression method="equals" channel_variable="status"
				value="Pending CoF" type="String" />
		</expression>
	</rule>
	<!-- Contract Budget List ends -->

	<rule id="isProposalReturnedForRevision">
		<expression method="equals" channel_variable="statusId"
			value="19" type="String" />
	</rule>
	<rule id="isProposalSubmitted">
		<expression method="equals" channel_variable="statusId"
			value="18" type="String" />
	</rule>
	<rule id="rule1">
		<expression operator="and">
			<expression method="equals" channel_variable="role" value="L2Provider"
				type="String" />
			<expression operator="or">
				<expression method="equals" channel_variable="status"
					type="String" value="Pending Submission" />
				<expression operator="or">
					<expression method="equals" channel_variable="status"
						type="String" value="Pending Submission" />
					<expression method="equals" channel_variable="status"
						type="String" value="Returned for Revision" />
				</expression>
			</expression>
		</expression>
	</rule>
	<rule id="rule2">
		<expression operator="and">
			<expression method="equals" channel_variable="role" value="L2Provider"
				type="String" />
			<expression operator="or">
				<expression method="equals" channel_variable="status"
					type="String" value="Pending Submission" />
				<expression operator="or">
					<expression method="equals" channel_variable="status"
						type="String" value="Pending Submission" />
					<expression method="equals" channel_variable="status"
						type="String" value="Returned for Revision" />
				</expression>
			</expression>
		</expression>
	</rule>
	<rule id="ruleContractStatusToContractNoAgency">
		<expression operator="or">
			<expression method="equals" channel_variable="role" value="L2Provider"
				type="String" />
			<expression method="equals" channel_variable="role" value="L2Provider"
				type="String" />
			<expression method="equals" channel_variable="role" value="3"
				type="String" />
			<expression method="equals" channel_variable="role" value="1"
				type="String" />
		</expression>
	</rule>
	<rule id="ruleContractStatusToContractNoProvider">
		<expression operator="or">
			<expression method="equals" channel_variable="role" value="L2Provider"
				type="String" />
			<expression method="equals" channel_variable="role" value="L2Provider"
				type="String" />
			<expression method="equals" channel_variable="role" value="3"
				type="String" />
			<expression method="equals" channel_variable="role" value="1"
				type="String" />
		</expression>
	</rule>

	<rule id="statusReturnNoPublicCommentLevel1">
		<expression operator="and">
			<expression method="equals" channel_variable="selectedStatus"
				value="Return" type="String" />
			<expression method="equals" channel_variable="publicComments"
				value="" type="String" />
			<expression method="equals" channel_variable="levelAgency"
				value="1" type="Integer" />
		</expression>
	</rule>

	<rule id="statusReturnNoInternalCommentLevel2">
		<expression operator="and">
			<expression method="equals" channel_variable="selectedStatus"
